workflows:
  web-profile-release:
    name: Web Profile release
    instance_type: mac_mini_m2
    environment:
      flutter: 3.29.1
      groups:
        - dev
    scripts:
      - name: Change Web app name
        script: |
          flutter pub add rename
          dart pub global activate rename
          rename setAppName --targets web --value $APP_NAME

      # - name: Download and unzip assets
      #   script: |
      #     echo "Downloading assets from $WEB_ASSETS_URL"
      #     curl -O $ASSETS_URL || echo "Failed to download assets"
      #     echo "Unzipping assets.zip"
      #     unzip -o assets.zip || echo "Failed to unzip assets.zip"

      - name: Download and unzip Web App Icon
        script: |
          echo "Downloading icon from $WEB_ICON"
          curl -O $WEB_ICON || echo "Failed to download app_icons.zip"
          echo "Unzipping app_icons.zip"
          unzip -o app_icons.zip -d web/icons || echo "Failed to unzip app_icons.zip"

      - name: Install dependencies
        script: |
          flutter packages pub get 

      - name: Flutter build after package name change
        script: |
          flutter build web --profile

    artifacts:
      - build/web
